// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4OhDadYShsKTliUzFPT0oitK5uoABlD8',
    appId: '1:640893556568:web:ab2580da4106812446b72d',
    messagingSenderId: '640893556568',
    projectId: 'applicationhiit',
    authDomain: 'applicationhiit.firebaseapp.com',
    storageBucket: 'applicationhiit.appspot.com',
    measurementId: 'G-C1X2YD17BT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSkfMhW4PRh31fRCVDOehXpS-T1oXqNxw',
    appId: '1:640893556568:android:848c17e892a412b746b72d',
    messagingSenderId: '640893556568',
    projectId: 'applicationhiit',
    storageBucket: 'applicationhiit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8NmydiRw8fEEPWqW2wfeBXtJSgn-avyo',
    appId: '1:640893556568:ios:ee3cb500ccbabe9946b72d',
    messagingSenderId: '640893556568',
    projectId: 'applicationhiit',
    storageBucket: 'applicationhiit.appspot.com',
    iosClientId: '640893556568-ehqhtkljpcgpnta0ds6qpt8cp1u9hfq6.apps.googleusercontent.com',
    iosBundleId: 'com.example.applicationahiitAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8NmydiRw8fEEPWqW2wfeBXtJSgn-avyo',
    appId: '1:640893556568:ios:ee3cb500ccbabe9946b72d',
    messagingSenderId: '640893556568',
    projectId: 'applicationhiit',
    storageBucket: 'applicationhiit.appspot.com',
    iosClientId: '640893556568-ehqhtkljpcgpnta0ds6qpt8cp1u9hfq6.apps.googleusercontent.com',
    iosBundleId: 'com.example.applicationahiitAdmin',
  );
}
